
SELECT ItemID FROM Categories WHERE ItemID NOT IN (SELECT ItemID FROM Items);
SELECT ItemID FROM Bids WHERE ItemID NOT IN (SELECT ItemID FROM Items);
SELECT UserID FROM Bids WHERE UserID NOT IN (SELECT UserID FROM Users);
SELECT SellerID FROM Items WHERE SellerID NOT IN (SELECT UserID FROM Users);

